server:
  port: 8080
  max-http-header-size: 1048576
spring:
  jackson:
    time-zone: GMT+8
  jpa:
    generate-ddl: true
    database: mysql
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/face_warehouse?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: face-warehouse
eureka:
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://127.0.0.1:8888/eureka/